OC-8239:WS CRF import creates duplicate event CRF if a different CRF …
OpenClinica/OpenClinica pull request #3152
Opened 2020-07-22 19:52 UTC by Taoli2018

…version already has been started for that event.

2021-05-19 19:17 UTC, svadla-oc requested changes

2021-05-19 19:17 UTC, svadla-oc commented on ws/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
> +                    }
fix indentation in this class

2021-05-19 19:18 UTC, svadla-oc commented
create a PR for 3.17.x branch

2021-05-24 22:07 UTC, Taoli2018 commented on ws/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
> +                    }
fixed

2021-05-24 22:37 UTC, Taoli2018 commented
please see https://github.com/OpenClinica/OpenClinica/pull/3473 for 3.17 PR

2021-05-26 18:23 UTC, svadla-oc commented
Addressed in #3473

2021-05-26 18:23 UTC, closed without merging