OC-8254:Scheduled CRF import creates duplicate event CRF if a differe…
OpenClinica/OpenClinica pull request #3157
Opened 2020-07-23 19:52 UTC by Taoli2018

…nt CRF version already has been started for that event.

2021-05-19 19:13 UTC, svadla-oc requested changes

2021-05-19 19:13 UTC, svadla-oc commented on web/src/main/java/org/akaza/openclinica/web/job/ImportSpringJob.java
> +              			    }
fix indentation

2021-05-19 19:15 UTC, svadla-oc commented
This should be created for 3.17.x branch

2021-05-26 13:36 UTC, Taoli2018 commented
please also see new PR in 3.17x
https://github.com/OpenClinica/OpenClinica/pull/3474

2021-05-26 18:13 UTC, svadla-oc commented
Closing since this is included in #3474

2021-05-26 18:13 UTC, closed without merging