OC-9170:Marking a CRF Complete breaks navigating between sections of CRF
OpenClinica/OpenClinica pull request #3471
Opened 2021-05-24 20:09 UTC by Taoli2018

please see old PR #1447

2021-05-26 19:11 UTC, svadla-oc requested changes

2021-05-26 19:11 UTC, svadla-oc commented on web/src/main/webapp/includes/global_functions_javascript.js
> +    }
It looks like viewSectionDataEntry.jsp had commented out checkDataStatus function. These changes will bring back the checkDataStatus function for that jsp. We should verify why that function was commented out and whether it's ok to bring it back.

2021-05-26 19:11 UTC, svadla-oc commented on web/src/main/webapp/includes/global_functions_javascript.js
> +    }
There are some jsps that have this javascript file imported and also have these functions defined within the jsp file. We should make sure that these functions don't interfere with each other. E.g. administrativeEditing.jsp has this scenario.

2021-06-03 17:20 UTC, Taoli2018 commented
we did more testing on current code, even after roll back all code changes of "fix", still can't reproduce this issue any more, so this may related to temporarily browser render issue, at this time, we decide to not commit any code changes, if it happened again in the future, we'll come back to revisit this issue.

2021-06-03 17:20 UTC, closed without merging